version: '3'
services:
  jekyll-dw30:
    build: .
    ports:
    - "127.0.0.1:4000:4000"
    volumes:
    - .:/build
    command: bash -c "bundle update --bundler; bundle install ; bundle exec jekyll serve  --watch --host 0.0.0.0"
